=== geschwaerzler/xml-examples/lab/lab1/BilgicOeztuerk/wfac.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT tournament (description, discipline*, division*, athlete*, group*)>


<!ELEMENT description (#PCDATA)>

<!ELEMENT discipline (#PCDATA)>
<!ATTLIST discipline id ID 			#REQUIRED>

<!ELEMENT division (#PCDATA)>
<!ATTLIST division id ID #REQUIRED >

<!ELEMENT group (athlete*, round*)>
<!ATTLIST group
			name 			CDATA   #REQUIRED>
			
<!ELEMENT athlete EMPTY>
<!ATTLIST athlete
			id			ID	    #REQUIRED
			firstname	CDATA 	#REQUIRED
			lastname	CDATA	#REQUIRED
			country		CDATA 	#IMPLIED
		>
		
<!ELEMENT round (score-card*)>
<!ATTLIST round
			nr			CDATA   #REQUIRED
			date		CDATA 	#REQUIRED
		>
		
<!ELEMENT score-card (target*)>
<!ATTLIST score-card
			athlete-id	IDREF   #REQUIRED
		>
		
<!ELEMENT target (score*)>
<!ATTLIST target
			nr			CDATA   #REQUIRED
		>
		
<!ELEMENT score EMPTY>
<!ATTLIST score
			arrow-nr	CDATA   #REQUIRED
			points		CDATA	#REQUIRED
		>

=== geschwaerzler/xml-examples/lab/lab3/KocabySagdicSahin/wfac.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE tournament SYSTEM "wfac.dtd">

<tournament>

	<description>
		FH Dornbirn Archery Open 2021
	</description>

	<group nr="1">

		<athlete id="a-1" firstname="Franz" lastname="MÃ¼ller"
			club="AC Bregenz" />
		<athlete id="a-2" firstname="Martin" lastname="Spiegel"
			club="AC Dornbirn" />
		<athlete id="a-3" firstname="Paul" lastname="Antoni"
			club="AC Bludenz" />
		<athlete id="a-4" firstname="Sebastian" lastname="Decker"
			club="AC Feldkirch" />

		<round nr="1" date="2021-06-19">
			<score-card athlete-id="a-1">
				<target nr="1">
					<score arrow-nr="1" points="5" />
					<score arrow-nr="2" points="12" />
				</target>

				<target nr="2">
					<score arrow-nr="1" points="1" />
					<score arrow-nr="2" points="2" />
					<score arrow-nr="3" points="12" />
				</target>

				<target nr="3">
					<score arrow-nr="1" points="9" />
					<score arrow-nr="2" points="0" />
					<score arrow-nr="3" points="10" />
				</target>

				<target nr="4">
					<score arrow-nr="1" points="0" />
					<score arrow-nr="2" points="2" />
					<score arrow-nr="3" points="6" />
				</target>
			</score-card>

			<score-card athlete-id="a-2">
				<target nr="1">
					<score arrow-nr="1" points="10" />
					<score arrow-nr="2" points="12" />
				</target>

				<target nr="2">
					<score arrow-nr="1" points="11" />
					<score arrow-nr="2" points="12" />
				</target>

				<target nr="3">
					<score arrow-nr="1" points="9" />
					<score arrow-nr="2" points="0" />
					<score arrow-nr="3" points="12" />
				</target>

				<target nr="4">
					<score arrow-nr="1" points="0" />
					<score arrow-nr="2" points="8" />
					<score arrow-nr="3" points="11" />
				</target>
			</score-card>

			<score-card athlete-id="a-3">
				<target nr="1">
					<score arrow-nr="1" points="5" />
					<score arrow-nr="2" points="1" />
					<score arrow-nr="3" points="12" />
				</target>

				<target nr="2">
					<score arrow-nr="1" points="0" />
					<score arrow-nr="2" points="12" />
				</target>

				<target nr="3">
					<score arrow-nr="1" points="3" />
					<score arrow-nr="2" points="2" />
					<score arrow-nr="3" points="7" />
				</target>

				<target nr="4">
					<score arrow-nr="1" points="10" />
					<score arrow-nr="2" points="12" />
				</target>
			</score-card>

			<score-card athlete-id="a-4">
				<target nr="1">
					<score arrow-nr="1" points="1" />
					<score arrow-nr="2" points="0" />
					<score arrow-nr="3" points="1" />
				</target>

				<target nr="2">
					<score arrow-nr="1" points="12" />
				</target>

				<target nr="3">
					<score arrow-nr="1" points="3" />
					<score arrow-nr="2" points="6" />
					<score arrow-nr="3" points="12" />
				</target>

				<target nr="4">
					<score arrow-nr="1" points="12" />
				</target>
			</score-card>
		</round>
		
		<round nr="2" date="2021-06-20">
			<score-card athlete-id="a-1">
				<target nr="1">
					<score arrow-nr="1" points="3" />
					<score arrow-nr="2" points="8" />
					<score arrow-nr="3" points="11" />
				</target>

				<target nr="2">
					<score arrow-nr="1" points="10" />
					<score arrow-nr="2" points="12" />
				</target>

				<target nr="3">
					<score arrow-nr="1" points="7" />
					<score arrow-nr="2" points="0" />
					<score arrow-nr="3" points="8" />
				</target>

				<target nr="4">
					<score arrow-nr="1" points="9" />
					<score arrow-nr="2" points="12" />
				</target>
			</score-card>

			<score-card athlete-id="a-2">
				<target nr="1">
					<score arrow-nr="1" points="12" />
				</target>

				<target nr="2">
					<score arrow-nr="1" points="1" />
					<score arrow-nr="2" points="5" />
					<score arrow-nr="2" points="12" />
				</target>

				<target nr="3">
					<score arrow-nr="1" points="9" />
					<score arrow-nr="2" points="0" />
					<score arrow-nr="3" points="12" />
				</target>

				<target nr="4">
					<score arrow-nr="1" points="0" />
					<score arrow-nr="2" points="8" />
					<score arrow-nr="3" points="11" />
				</target>
			</score-card>

			<score-card athlete-id="a-3">
				<target nr="1">
					<score arrow-nr="1" points="5" />
					<score arrow-nr="2" points="1" />
					<score arrow-nr="3" points="12" />
				</target>

				<target nr="2">
					<score arrow-nr="1" points="0" />
					<score arrow-nr="2" points="12" />
				</target>

				<target nr="3">
					<score arrow-nr="1" points="3" />
					<score arrow-nr="2" points="2" />
					<score arrow-nr="3" points="7" />
				</target>

				<target nr="4">
					<score arrow-nr="1" points="10" />
					<score arrow-nr="2" points="12" />
				</target>
			</score-card>

			<score-card athlete-id="a-4">
				<target nr="1">
					<score arrow-nr="1" points="1" />
					<score arrow-nr="2" points="0" />
					<score arrow-nr="3" points="1" />
				</target>

				<target nr="2">
					<score arrow-nr="1" points="12" />
				</target>

				<target nr="3">
					<score arrow-nr="1" points="3" />
					<score arrow-nr="2" points="6" />
					<score arrow-nr="3" points="12" />
				</target>

				<target nr="4">
					<score arrow-nr="1" points="12" />
				</target>
			</score-card>
		</round>

		<round nr="3" date="2021-06-21">
			<score-card athlete-id="a-1">
				<target nr="1">
					<score arrow-nr="1" points="5" />
					<score arrow-nr="2" points="6" />
					<score arrow-nr="3" points="8" />
				</target>

				<target nr="2">
					<score arrow-nr="1" points="6" />
					<score arrow-nr="2" points="11" />
					<score arrow-nr="3" points="12" />
				</target>

				<target nr="3">
					<score arrow-nr="1" points="1" />
					<score arrow-nr="2" points="6" />
					<score arrow-nr="3" points="10" />
				</target>

				<target nr="4">
					<score arrow-nr="1" points="12" />
				</target>
			</score-card>

			<score-card athlete-id="a-2">
				<target nr="1">
					<score arrow-nr="1" points="1" />
					<score arrow-nr="2" points="9" />
					<score arrow-nr="3" points="12" />
				</target>

				<target nr="2">
					<score arrow-nr="1" points="6" />
					<score arrow-nr="2" points="8" />
					<score arrow-nr="3" points="9" />
				</target>

				<target nr="3">
					<score arrow-nr="1" points="6" />
					<score arrow-nr="2" points="12" />
				</target>

				<target nr="4">
					<score arrow-nr="1" points="1" />
					<score arrow-nr="2" points="8" />
					<score arrow-nr="3" points="12" />
				</target>
			</score-card>

			<score-card athlete-id="a-3">
				<target nr="1">
					<score arrow-nr="1" points="10" />
					<score arrow-nr="2" points="12" />
				</target>

				<target nr="2">
					<score arrow-nr="1" points="6" />
					<score arrow-nr="2" points="8" />
					<score arrow-nr="3" points="12" />
				</target>

				<target nr="3">
					<score arrow-nr="1" points="3" />
					<score arrow-nr="2" points="6" />
					<score arrow-nr="3" points="12" />
				</target>

				<target nr="4">
					<score arrow-nr="1" points="1" />
					<score arrow-nr="2" points="12" />
				</target>
			</score-card>

			<score-card athlete-id="a-4">
				<target nr="1">
					<score arrow-nr="1" points="5" />
					<score arrow-nr="2" points="10" />
					<score arrow-nr="3" points="12" />
				</target>

				<target nr="2">
					<score arrow-nr="1" points="8" />
					<score arrow-nr="2" points="9" />
					<score arrow-nr="3" points="12" />
				</target>

				<target nr="3">
					<score arrow-nr="1" points="1" />
					<score arrow-nr="2" points="1" />
					<score arrow-nr="3" points="12" />
				</target>

				<target nr="4">
					<score arrow-nr="1" points="1" />
					<score arrow-nr="2" points="4" />
					<score arrow-nr="3" points="5" />
				</target>
			</score-card>
		</round>

		<round nr="4" date="2021-06-22">
			<score-card athlete-id="a-1">
				<target nr="1">
					<score arrow-nr="1" points="5" />
					<score arrow-nr="2" points="6" />
					<score arrow-nr="3" points="12" />
				</target>

				<target nr="2">
					<score arrow-nr="1" points="6" />
					<score arrow-nr="2" points="11" />
					<score arrow-nr="3" points="8" />
				</target>

				<target nr="3">
					<score arrow-nr="1" points="1" />
					<score arrow-nr="2" points="6" />
					<score arrow-nr="3" points="10" />
				</target>

				<target nr="4">
					<score arrow-nr="1" points="12" />
				</target>
			</score-card>

			<score-card athlete-id="a-2">
				<target nr="1">
					<score arrow-nr="1" points="1" />
					<score arrow-nr="2" points="9" />
					<score arrow-nr="3" points="11" />
				</target>

				<target nr="2">
					<score arrow-nr="1" points="6" />
					<score arrow-nr="2" points="8" />
					<score arrow-nr="3" points="11" />
				</target>

				<target nr="3">
					<score arrow-nr="1" points="6" />
					<score arrow-nr="2" points="12" />
				</target>

				<target nr="4">
					<score arrow-nr="1" points="1" />
					<score arrow-nr="2" points="8" />
					<score arrow-nr="3" points="8" />
				</target>
			</score-card>

			<score-card athlete-id="a-3">
				<target nr="1">
					<score arrow-nr="1" points="10" />
					<score arrow-nr="2" points="12" />
				</target>

				<target nr="2">
					<score arrow-nr="1" points="6" />
					<score arrow-nr="2" points="8" />
					<score arrow-nr="3" points="8" />
				</target>

				<target nr="3">
					<score arrow-nr="1" points="3" />
					<score arrow-nr="2" points="6" />
					<score arrow-nr="3" points="10" />
				</target>

				<target nr="4">
					<score arrow-nr="1" points="1" />
					<score arrow-nr="2" points="12" />
				</target>
			</score-card>

			<score-card athlete-id="a-4">
				<target nr="1">
					<score arrow-nr="1" points="5" />
