=== geschwaerzler/xml-examples/lab/lab2/G2-Guezel-Sebastian-Yildrimin-Sahin/music_database.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT music_database (person+, genre+, song+, album+)>

<!ELEMENT person (musician?,songwriter?)>
<!ATTLIST person
	id			ID		#REQUIRED
	first_name 	CDATA	#REQUIRED
	last_name	CDATA	#REQUIRED
	artist_name CDATA	#IMPLIED
	birthday	CDATA	#REQUIRED
	dateOfDeath CDATA	#IMPLIED
	listensto	IDREF	#IMPLIED
>

<!ELEMENT musician EMPTY>
<!ATTLIST musician
	id			ID		#REQUIRED
	follower	CDATA 	#REQUIRED
	band 		CDATA	#IMPLIED
	company		CDATA	#IMPLIED
>

<!ELEMENT songwriter EMPTY>
<!ATTLIST songwriter
	id		ID		#REQUIRED
	company CDATA	#IMPLIED
>

<!ELEMENT genre (has+)>
<!ATTLIST genre
	id		ID		#REQUIRED
	name	CDATA 	#REQUIRED
>

<!ELEMENT has EMPTY>
<!ATTLIST has
	song_id IDREF	#REQUIRED
>

<!ELEMENT song (sings_song*,writes_song+)>
<!ATTLIST song
	id				ID		#REQUIRED
	title			CDATA	#REQUIRED
	release_date	CDATA	#REQUIRED
	duration		CDATA	#REQUIRED	
>

<!ELEMENT sings_song EMPTY>
<!ATTLIST sings_song
	person_id	IDREF	#REQUIRED
>

<!ELEMENT writes_song EMPTY>
<!ATTLIST writes_song
	person_id	IDREF	#REQUIRED
>

<!ELEMENT album	(contains+)>
<!ATTLIST album
	album_id		ID		#REQUIRED
	album_name		CDATA	#REQUIRED
	release_date	CDATA	#REQUIRED
	musician_id		IDREF	#REQUIRED
>

<!ELEMENT contains EMPTY>
<!ATTLIST contains
	song_id IDREF	#REQUIRED
>

=== geschwaerzler/xml-examples/lab/lab1/G2-Guezel-Sebastian-Yildrimin-Sahin/music_database.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE music_database SYSTEM "music_database.dtd">
<music_database>

	<!--Only Musician-->
	<person id="person-1" first_name="Justin" last_name="Bieber" artist_name="JB" birthday="01.04.1994">
		<musician id="musician-1" follower="75500000" band="HATE ME"></musician>
		<songwriter id="songwriter-10"></songwriter>
	</person>
	
	<person id="person-2" first_name="Ariane" last_name="Grande" birthday="26.06.2000">
		<musician id="musician-2" follower="889002000"></musician>
	</person>
	
	<person id="person-3" first_name="Justin" last_name="Timberlake" artist_name="JT" birthday="31.01.1980">
		<musician id="musician-3" follower="45000000"></musician>
	</person>
	
	<person id="person-4" first_name="Miley" last_name="Cyrus" artist_name="Hannah Montana" birthday="23.11.1992">
		<musician id="musician-4" follower="1500000" company="Abzocke"></musician>
	</person>
	
	<person id="person-14" first_name="Nicki" last_name="Minaj" birthday="08.12.1982">
		<musician id="musician-8" follower="50000000"></musician>
	</person>
	
	
	<!--Musician and Songwriter-->
	<person id="person-5" first_name="John" last_name="Lennon" artist_name="null" birthday="09.10.1940" dateOfDeath="08.12.1980">
		<musician id="musician-5" follower="2230000" band="The Beatles" company="null"></musician>
		<songwriter id="songwriter-5" company="Abzocke"></songwriter>
	</person> 
	
	<person id="person-6" first_name="Paul" last_name="McCartney" artist_name="null" birthday="18.06.1942">
		<musician id="musician-6" follower="15000000" band="The Beatles" company="null"></musician>
		<songwriter id="songwriter-6"></songwriter>
	</person>
	
	<person id="person-7" first_name="Selena" last_name="Gomez" artist_name="null" birthday="22.07.1992">
			<musician id="musician-7" follower="200000000" band="null" company="null"></musician>
			<songwriter id="songwriter-7"></songwriter>
	</person>
	
	<person id="person-18" first_name="Charlton" last_name="Howard" artist_name="the Kid LAROI" birthday="17.08.2003">
		<musician id="musician-9" follower="34000000"></musician>
		<songwriter id="songwriter-17"></songwriter>
	</person>
	
	<person id="person-19" first_name="Isabelle" last_name="Geffroy" artist_name="Zaz" birthday="01.05.1980">
		<musician id="musician-10" follower="2600000"></musician>
		<songwriter id="songwriter-18"></songwriter>
	</person>
	
	
	<!--Music Listeners-->
	<person id="person-8" first_name="Efza" last_name="Yildirim" artist_name="" birthday="08.03.2002" dateOfDeath="null" listensto="song-1"></person>
	<person id="person-9" first_name="Melih" last_name="Sahin" artist_name="" birthday="08.12.2001" dateOfDeath="null" listensto="song-5"></person>
	<person id="person-10" first_name="John" last_name="Wick" artist_name="" birthday="18.03.1970" dateOfDeath="19.03.2023"></person>
	
	<!--Only Songwriter-->
	<person id="person-11" first_name="Benny" last_name="Blanco" artist_name="null" birthday="08.03.1988" dateOfDeath="null">
		<songwriter id="songwriter-11" company="Interscope Records"></songwriter>
	</person>
	
	<person id="person-12" first_name="Rami" last_name="Yacoub" artist_name="null" birthday="17.01.1975" dateOfDeath="null">
		<songwriter id="songwriter-12" company="null"></songwriter>
	</person>
	
	<person id="person-13" first_name="Michael" last_name="Masser" artist_name="null" birthday="24.03.1941" dateOfDeath="null">
		<songwriter id="songwriter-13" company="Arista-Records"></songwriter>	
	</person>
	
	<person id="person-15" first_name="Max" last_name="Martin" birthday="26.02.1971">
		<songwriter id="songwriter-14"></songwriter>
	</person>
	
	<person id="person-16" first_name="Timothy" last_name="Mosley" artist_name="Timbaland" birthday="10.03.1972">
		<songwriter id="songwriter-15"></songwriter>
	</person>
	
	<person id="person-17" first_name="Ryan" last_name="Tedder" birthday="26.06.1979">
		<songwriter id="songwriter-16"></songwriter>
	</person>


	<genre id="genre-1" name="pop">
		<has song_id="song-1"></has>
		<has song_id="song-2"></has>
		<has song_id="song-3"></has>
		<has song_id="song-6"></has>
		<has song_id="song-20"></has>
		<has song_id="song-21"></has>
		<has song_id="song-22"></has>
		<has song_id="song-24"></has>
		<has song_id="song-26"></has>
	</genre>
	<genre id="genre-2" name="rock">
		<has song_id="song-4"></has>
		<has song_id="song-17"></has>
		<has song_id="song-18"></has>
		<has song_id="song-19"></has>
		<has song_id="song-20"></has>
		<has song_id="song-22"></has>
		<has song_id="song-23"></has>
		<has song_id="song-24"></has>
		<has song_id="song-25"></has>
	</genre>
	<genre id="genre-3" name="alternative">
		<has song_id="song-8"></has>
		<has song_id="song-9"></has>
		<has song_id="song-10"></has>
		<has song_id="song-11"></has>
		<has song_id="song-12"></has>
		<has song_id="song-13"></has>
		<has song_id="song-14"></has>
		<has song_id="song-15"></has>
		<has song_id="song-29"></has>
		<has song_id="song-30"></has>
	</genre>
	<genre id="genre-4" name="afrobeats">
		<has song_id="song-5"></has>
	</genre>
	<genre id="genre-5" name="ballade">
		<has song_id="song-16"></has>
	</genre>
	<genre id="genre-6" name="funk">
		<has song_id="song-23"></has>
	</genre>
	<genre id="genre-7" name="jazz">
		<has song_id="song-27"></has>
		<has song_id="song-28"></has>
		<has song_id="song-29"></has>
		<has song_id="song-30"></has>
		<has song_id="song-31"></has>
		<has song_id="song-32"></has>
		<has song_id="song-33"></has>
		<has song_id="song-34"></has>
		<has song_id="song-35"></has>
		<has song_id="song-36"></has>
		<has song_id="song-37"></has>
		<has song_id="song-38"></has>
	</genre>
	
	<!--Songs-->
	<song id="song-1" title="STAY" release_date="2021" duration="157">
		<sings_song person_id="person-1"></sings_song>
		<writes_song person_id="person-1"></writes_song>
	</song>
	
	<song id="song-2" title="Side to Side" release_date="2016" duration="237">
		<sings_song person_id="person-2"></sings_song>
		<sings_song person_id="person-14"></sings_song>
		<writes_song person_id="person-15"></writes_song>
	</song>
	
	<song id="song-3" title="Cry me a river" release_date="1998" duration="290">
		<sings_song person_id="person-3"></sings_song>
		<writes_song person_id="person-16"></writes_song>
	</song>
	
	<song id="song-4" title="Angles Like You" release_date="2020" duration="245">
		<sings_song person_id="person-4"></sings_song>
		<writes_song person_id="person-17"></writes_song>
	</song>
	
	<song id="song-5" title="Calm Down" release_date="2022" duration="239">
		<sings_song person_id="person-7"></sings_song>
		<writes_song person_id="person-7"></writes_song>
	</song>
	
	<song id="song-6" title="Let It Be" release_date="1970" duration="239">
		<sings_song person_id="person-5"></sings_song>
		<sings_song person_id="person-6"></sings_song>
		<writes_song person_id="person-6"></writes_song>
		<writes_song person_id="person-13"></writes_song>
	</song>
	
	<song id="song-7" title="OVER YOU" release_date="2021" duration="150">
		<sings_song person_id="person-18"></sings_song>
		<writes_song person_id="person-18"></writes_song>
	</song>
	
	<song id="song-8" title="NOT SOBER" release_date="2021" duration="216">
		<sings_song person_id="person-18"></sings_song>
		<writes_song person_id="person-18"></writes_song>
	</song>
	
	<song id="song-9" title="SAME ENERGY" release_date="2021" duration="93">
		<sings_song person_id="person-18"></sings_song>
		<writes_song person_id="person-18"></writes_song>
	</song>
	
	<song id="song-10" title="DON'T LEAVE ME" release_date="2021" duration="167">
		<sings_song person_id="person-18"></sings_song>
		<writes_song person_id="person-18"></writes_song>
	</song>
	
	<song id="song-11" title="BAD NEWS" release_date="2021" duration="131">
		<sings_song person_id="person-18"></sings_song>
		<writes_song person_id="person-18"></writes_song>
	</song>
	
	<song id="song-12" title="STILL CHOSE YOU" release_date="2021" duration="171">
		<sings_song person_id="person-18"></sings_song>
		<writes_song person_id="person-18"></writes_song>
	</song>
	
	<song id="song-13" title="I DON'T KNOW" release_date="2021" duration="134">
		<sings_song person_id="person-18"></sings_song>
		<writes_song person_id="person-18"></writes_song>
	</song>
	
	<song id="song-14" title="ABOUT YOU" release_date="2021" duration="128">
		<sings_song person_id="person-18"></sings_song>
		<writes_song person_id="person-18"></writes_song>
	</song>
	
	<song id="song-15" title="LONELY AND F*CKED UP" release_date="2021" duration="162">
		<sings_song person_id="person-18"></sings_song>
		<writes_song person_id="person-18"></writes_song>
	</song>
	
	<song id="song-16" title="Imagine" release_date="1971" duration="187">
		<sings_song person_id="person-5"></sings_song>
		<writes_song person_id="person-5"></writes_song>
	</song>
	
	<song id="song-17" title="Crippled Inside" release_date="1971" duration="232">
		<sings_song person_id="person-5"></sings_song>
		<writes_song person_id="person-5"></writes_song>
	</song>
	
	<song id="song-18" title="Jealous Guy" release_date="1971" duration="257">
		<sings_song person_id="person-5"></sings_song>
		<writes_song person_id="person-5"></writes_song>
	</song>
	
	<song id="song-19" title="It's so hard" release_date="1971" duration="149">
		<sings_song person_id="person-5"></sings_song>
		<writes_song person_id="person-5"></writes_song>
	</song>
	
	<song id="song-20" title="I Don't Wanna Be A Soldier Mama" release_date="1971" duration="368">
		<sings_song person_id="person-5"></sings_song>
		<writes_song person_id="person-5"></writes_song>
	</song>
	
	<song id="song-21" title="Gimme Some Truth" release_date="1971" duration="197">
		<sings_song person_id="person-5"></sings_song>
		<writes_song person_id="person-5"></writes_song>
	</song>
	
	<song id="song-22" title="Oh My Love" release_date="1971" duration="168">
		<sings_song person_id="person-5"></sings_song>
		<writes_song person_id="person-5"></writes_song>
	</song>
