=== geschwaerzler/xml-examples/lab/lab2/ChuhanKarakusKilicKreil/archery-tournament.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT bow-tournament (division*, discipline*, archer*, target*, point*, group*)>

<!ELEMENT division (#PCDATA)>
<!ATTLIST division id ID #REQUIRED>

<!ELEMENT discipline (#PCDATA)>
<!ATTLIST discipline id ID #REQUIRED>

<!ELEMENT archer (firstname, lastname, birthday)>
<!ATTLIST archer id ID #REQUIRED>
<!ATTLIST archer gender CDATA #REQUIRED>
<!ELEMENT firstname (#PCDATA)>
<!ELEMENT lastname (#PCDATA)>
<!ELEMENT birthday (#PCDATA)>

<!ELEMENT group (member*)>
<!ATTLIST group
    name CDATA #REQUIRED
    division-id IDREF #REQUIRED
    discipline-id IDREF #REQUIRED
    tag CDATA #REQUIRED
>

<!ELEMENT member (score*)>
<!ATTLIST member archer-id IDREF #REQUIRED>

<!ELEMENT score (arrow*)>
<!ATTLIST score target-id IDREF #REQUIRED>

<!ELEMENT arrow EMPTY>
<!ATTLIST arrow 
	pID IDREF #REQUIRED
	points CDATA #REQUIRED
>


<!ELEMENT target (#PCDATA)>
<!ATTLIST target
	id ID #REQUIRED
	name CDATA #REQUIRED
>

<!ELEMENT point (#PCDATA)>
<!ATTLIST point
	pID ID #REQUIRED
	pname CDATA #REQUIRED
>

=== geschwaerzler/xml-examples/lab/lab1/ChuhanKarakusKilicKreil/message.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bow-tournament SYSTEM "archery-tournament.dtd">

<bow-tournament>
	<division id="D1">Recurve Division</division>
	<division id="D2">Compound Division</division>
	<division id="D3">Barebow Division</division>
	
	<discipline id="B1">Outdoor Archery</discipline>
	<discipline id="B2">Field Archery</discipline>
	<discipline id="B3">Run Archery</discipline>
	
	<archer id="a1" gender="male">
		<firstname>Dennis</firstname>
		<lastname>Kreil</lastname>
		<birthday>2000-10-29</birthday>
	</archer>
	
	<archer id="a2" gender="male">
		<firstname>Furkan</firstname>
		<lastname>Kilic</lastname>
		<birthday>2003-03-11</birthday>
	</archer>
	
	<archer id="a3" gender="male">
		<firstname>Mikail</firstname>
		<lastname>Karakus</lastname>
		<birthday>2000-08-15</birthday>
	</archer>
	
	<archer id="a4" gender="female">
		<firstname>Nina</firstname>
		<lastname>Hartmann</lastname>
		<birthday>2001-06-13</birthday>
	</archer>
	
	<archer id="a5" gender="female">
		<firstname>Haris</firstname>
		<lastname>Chuhan</lastname>
		<birthday>1999-06-28</birthday>
	</archer>
	
	<archer id="a6" gender="female">
		<firstname>Stefan</firstname>
		<lastname>Raab</lastname>
		<birthday>2001-06-13</birthday>
	</archer>
	
	<archer id="a7" gender="female">
		<firstname>Sebastian</firstname>
		<lastname>Fischer</lastname>
		<birthday>1999-04-12</birthday>
	</archer>
	
	<archer id="a8" gender="male">
		<firstname>Zlatan</firstname>
		<lastname>Ibrahimovic</lastname>
		<birthday>1984-04-23</birthday>
	</archer>
	
	<archer id="a9" gender="male">
		<firstname>Antony</firstname>
		<lastname>Matheus dos Santos</lastname>
		<birthday>2000-02-24</birthday>
	</archer>
	
	<archer id="a10" gender="male">
		<firstname>Sebastian</firstname>
		<lastname>Haller</lastname>
		<birthday>1994-06-22</birthday>
	</archer>
	
	<archer id="a11" gender="male">
		<firstname>Karim</firstname>
		<lastname>Benzema</lastname>
		<birthday>1987-12-19</birthday>
	</archer>
	
	<archer id="a12" gender="male">
		<firstname>Vinicius</firstname>
		<lastname>Junior</lastname>
		<birthday>2000-07-12</birthday>
	</archer>
	
	<archer id="a13" gender="male">
		<firstname>Kylian</firstname>
		<lastname>Mbappe</lastname>
		<birthday>1998-12-20</birthday>
	</archer>
	
	<archer id="a14" gender="male">
		<firstname>Erling</firstname>
		<lastname>Haaland</lastname>
		<birthday>2000-07-21</birthday>
	</archer>
	
	<archer id="a15" gender="male">
		<firstname>Marco</firstname>
		<lastname>Reus</lastname>
		<birthday>1989-05-31</birthday>
	</archer>
	
	<archer id="a16" gender="male">
		<firstname>Miura</firstname>
		<lastname>Kazuyoshi</lastname>
		<birthday>1967-02-26</birthday>
	</archer>
	
	<target id="t1" name="50m"/>
	<target id="t2" name="100m"/>
	<target id="t3" name="125m"/>
	
	<group name="Gruppe Recurve Outdoor" division-id="D1" discipline-id="B1">
		<member archer-id="a1"> 
			<score target-id="t1">
				<arrow points="100"/>
				<arrow points="150"/>
				<arrow points="0"/>			
			</score>
			<score target-id="t2">
				<arrow points="170"/>
				<arrow points="180"/>
				<arrow points="200"/>			
			</score>
			<score target-id="t3">
				<arrow points="250"/>
				<arrow points="180"/>
				<arrow points="200"/>			
			</score>
		</member>
		<member archer-id="a2">
			<score target-id="t1">
				<arrow points="220"/>
				<arrow points="150"/>
				<arrow points="280"/>			
			</score>
			<score target-id="t2">
				<arrow points="80"/>
				<arrow points="100"/>
				<arrow points="0"/>			
			</score>
			<score target-id="t3">
				<arrow points="130"/>
				<arrow points="30"/>
				<arrow points="250"/>			
			</score>
		</member>
		<member archer-id="a3">
			<score target-id="t1">
				<arrow points="210"/>
				<arrow points="130"/>
				<arrow points="180"/>			
			</score>
			<score target-id="t2">
				<arrow points="200"/>
				<arrow points="220"/>
				<arrow points="250"/>			
			</score>
			<score target-id="t3">
				<arrow points="280"/>
				<arrow points="100"/>
				<arrow points="200"/>			
			</score>
		</member>		
	</group>
	
	<group name="Gruppe Compound Division" division-id="D2" discipline-id="B2">
		
		<member archer-id="a4"/>
			<score target-id="t1">
				<arrow points="100"/>
				<arrow points="150"/>
				<arrow points="0"/>			
			</score>
			<score target-id="t2">
				<arrow points="170"/>
				<arrow points="180"/>
				<arrow points="200"/>			
			</score>
			<score target-id="t3">
				<arrow points="250"/>
				<arrow points="180"/>
				<arrow points="200"/>			
			</score>
		</member>
		
		<member archer-id="a5"/>
			<score target-id="t1">
				<arrow points="100"/>
				<arrow points="150"/>
				<arrow points="0"/>			
			</score>
			<score target-id="t2">
				<arrow points="170"/>
				<arrow points="180"/>
				<arrow points="200"/>			
			</score>
			<score target-id="t3">
				<arrow points="250"/>
				<arrow points="180"/>
				<arrow points="200"/>			
			</score>
		</member>

		<member archer-id="a6"/>
			<score target-id="t1">
				<arrow points="100"/>
				<arrow points="150"/>
				<arrow points="0"/>			
			</score>
			<score target-id="t2">
				<arrow points="170"/>
				<arrow points="180"/>
				<arrow points="200"/>			
			</score>
			<score target-id="t3">
				<arrow points="250"/>
				<arrow points="180"/>
				<arrow points="200"/>			
			</score>
		</member>		
	</group>
	
	<group name="Gruppe Barebow Division" division-id="D3" discipline-id="B3">
		<member archer-id="a7"/>
			<score target-id="t1">
				<arrow points="100"/>
				<arrow points="150"/>
				<arrow points="0"/>			
			</score>
			<score target-id="t2">
				<arrow points="170"/>
				<arrow points="180"/>
				<arrow points="200"/>			
			</score>
			<score target-id="t3">
				<arrow points="250"/>
				<arrow points="180"/>
				<arrow points="200"/>			
			</score>
		</member>
		
		<member archer-id="a8"/>
			<score target-id="t1">
				<arrow points="100"/>
				<arrow points="150"/>
				<arrow points="0"/>			
			</score>
			<score target-id="t2">
				<arrow points="170"/>
				<arrow points="180"/>
				<arrow points="200"/>			
			</score>
			<score target-id="t3">
				<arrow points="250"/>
				<arrow points="180"/>
				<arrow points="200"/>			
			</score>
		</member>
		
		<member archer-id="a9"/>
			<score target-id="t1">
				<arrow points="0"/>
				<arrow points="0"/>
				<arrow points="0"/>			
			</score>
			<score target-id="t2">
				<arrow points="50"/>
				<arrow points="25"/>
				<arrow points="0"/>			
			</score>
			<score target-id="t3">
				<arrow points="100"/>
				<arrow points="50"/>
				<arrow points="0"/>			
			</score>
		</member>
		
		<group name="Gruppe Bowhunter Fingers Division" division-id="D4" discipline-id="B4">
		
		<member archer-id="a10"/>
			<score target-id="t1">
				<arrow points="200"/>
				<arrow points="250"/>
				<arrow points="250"/>			
			</score>
			<score target-id="t2">
				<arrow points="300"/>
				<arrow points="300"/>
				<arrow points="300"/>			
			</score>
			<score target-id="t3">
				<arrow points="250"/>
				<arrow points="300"/>
				<arrow points="200"/>			
			</score>
		</member>	
		
		<member archer-id="a11"/>
			<score target-id="t1">
				<arrow points="65"/>
				<arrow points="250"/>
				<arrow points="0"/>			
			</score>
			<score target-id="t2">
				<arrow points="80"/>
				<arrow points="250"/>
				<arrow points="50"/>			
			</score>
			<score target-id="t3">
				<arrow points="250"/>
				<arrow points="300"/>
				<arrow points="0"/>			
			</score>
		</member>	
		
		<member archer-id="a12"/>
			<score target-id="t1">
				<arrow points="45"/>
				<arrow points="55"/>
				<arrow points="65"/>			
			</score>
			<score target-id="t2">
				<arrow points="80"/>
				<arrow points="100"/>
				<arrow points="150"/>			
			</score>
			<score target-id="t3">
				<arrow points="250"/>
				<arrow points="0"/>
				<arrow points="150"/>			
			</score>
		</member>
	</group>
	
	<group name="Gruppe Bowhunter Release Division" division-id="D3" discipline-id="B3">

		<member archer-id="a13"/>
			<score target-id="t1">
				<arrow points="100"/>
				<arrow points="100"/>
				<arrow points="0"/>			
			</score>
			<score target-id="t2">
				<arrow points="200"/>
				<arrow points="180"/>
				<arrow points="200"/>			
			</score>
			<score target-id="t3">
				<arrow points="250"/>
				<arrow points="300"/>
				<arrow points="200"/>			
			</score>
		</member>
		
		<member archer-id="a14"/>
			<score target-id="t1">
				<arrow points="0"/>
				<arrow points="250"/>
				<arrow points="50"/>			
			</score>
			<score target-id="t2">
				<arrow points="0"/>
				<arrow points="30"/>
				<arrow points="300"/>			
			</score>
			<score target-id="t3">
				<arrow points="0"/>
				<arrow points="0"/>
				<arrow points="200"/>			
			</score>
		</member>
		
		<member archer-id="a15"/>
			<score target-id="t1">
				<arrow points="100"/>
				<arrow points="250"/>
				<arrow points="300"/>			
			</score>
			<score target-id="t2">
				<arrow points="150"/>
				<arrow points="200"/>
				<arrow points="200"/>			
			</score>
			<score target-id="t3">
				<arrow points="250"/>
				<arrow points="180"/>
				<arrow points="200"/>			
			</score>
		</member>
		
		<member archer-id="a16"/>
			<score target-id="t1">
				<arrow points="100"/>
				<arrow points="150"/>
				<arrow points="0"/>			
			</score>
			<score target-id="t2">
				<arrow points="170"/>
				<arrow points="180"/>
				<arrow points="200"/>			
			</score>
			<score target-id="t3">
				<arrow points="250"/>
				<arrow points="180"/>
				<arrow points="200"/>			
			</score>
		</member>
	</group>	
</bow-tournament>
