=== geschwaerzler/xml-examples/Dates/dates.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT some-days (date1+, date2)>

<!ELEMENT date1 EMPTY>
<!ATTLIST date1 day CDATA #REQUIRED
                month (1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12) #REQUIRED
                year  CDATA #REQUIRED
>


<!-- ELEMENT date2 (day, month, year) -->
<!-- ELEMENT date2 (day | month | year)* -->
<!ELEMENT date2 (
	(day, month+, year) |
	(day, year, month+) |
	(month+, day, year) |
	(month+, year, day) |
	(year, month+, day) |
	(year, day, month+)
)>
<!ELEMENT day (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT year (#PCDATA)>

=== geschwaerzler/xml-examples/Dates/dates.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE some-days SYSTEM "Dates.dtd">
<some-days>

	<date1 day="17" month="12" year="2019"/>
	<date1 month="12" day="17" year="2019"/>
	
	<date2>
		<day>17</day>
		<month>12</month>
		<month>Dezember</month>
		<year>2019</year>
	</date2>

</some-days>
