=== geschwaerzler/xml-examples/LabAssignments/XML_GronesGoenitzerRupp/aktiva.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT aktiva (company*, worker*, request*, offer*, qualification*)>

<!ELEMENT company (address+, company-contract*, contact)>
<!ATTLIST company
	id ID #REQUIRED
	name CDATA #REQUIRED
>

<!ELEMENT address EMPTY>
<!ATTLIST address
	country CDATA #REQUIRED
	zip CDATA #REQUIRED
	city CDATA #REQUIRED
	street CDATA #REQUIRED
>

<!ELEMENT company-contract EMPTY>
<!ATTLIST company-contract
	offer-id IDREF #REQUIRED
	hourly-wage CDATA #REQUIRED
>

<!ELEMENT contact EMPTY>
<!ATTLIST contact
	fname CDATA #REQUIRED
	lname CDATA #REQUIRED
	phonenumber CDATA #REQUIRED
	e-mail CDATA #REQUIRED
>


<!ELEMENT worker (address, cv-entry*, worker-contract*)>
<!ATTLIST worker
	id ID #REQUIRED
	fname CDATA #REQUIRED
	lname CDATA #REQUIRED
	phonenumber CDATA #REQUIRED
	e-mail CDATA #IMPLIED
	qualification IDREF #REQUIRED
>

<!ELEMENT cv-entry EMPTY>
<!ATTLIST cv-entry
	start CDATA #REQUIRED
	end CDATA #REQUIRED
	company-name CDATA #REQUIRED
>

<!ELEMENT worker-contract EMPTY>
<!ATTLIST worker-contract
	offer-id IDREF #REQUIRED
	hourly-wage CDATA #REQUIRED
>

<!ELEMENT request (denied-worker*, request-entry+)>
<!ATTLIST request
	id ID #REQUIRED
>

<!ELEMENT denied-worker EMPTY>
<!ATTLIST denied-worker
	worker-id IDREF #REQUIRED	
>

<!ELEMENT request-entry EMPTY>
<!ATTLIST request-entry
	start CDATA #REQUIRED
	end CDATA #IMPLIED
	qualification IDREF #REQUIRED
>

<!ELEMENT offer (offered-worker+)>
<!ATTLIST offer
	id ID #REQUIRED
	request-id IDREF #REQUIRED
>

<!ELEMENT offered-worker EMPTY>
<!ATTLIST offered-worker
	worker-id IDREF #REQUIRED
	hourly-rate CDATA #REQUIRED
>

<!ELEMENT qualification EMPTY>
<!ATTLIST qualification
	id ID #REQUIRED
	average-wage CDATA #REQUIRED
>

=== geschwaerzler/xml-examples/LabAssignments/XML_GronesGoenitzerRupp/aktiva.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE aktiva SYSTEM "aktiva.dtd">
<aktiva>
	
	<company id="company-1" name="FHV GmbH">
		<address country="AUT" zip="6850" city="Dornbirn" street="Hochschulstraße 1"/>
		<contact fname="Max" lname="Mustermann" phonenumber="6428429" e-mail="abc@gmx.at"/>
	</company>
	<company id="company-2" name="Grass">
		<address country="AUT" zip="6973" city="Höchst" street="Grass Platz 1"/>
		<contact fname="Gustav" lname="Klien" phonenumber="26497975168" e-mail="gustav@gmx.at"/>
	</company>
	<company id="company-3" name="I+R Gruppe GmbH">
		<address country="AUT" zip="6923" city="Lauterach" street="Johann-Schertler-Straße 1"/>
		<company-contract offer-id="offer-1" hourly-wage="20.00"/>
		<company-contract offer-id="offer-1" hourly-wage="19.00"/>
		<company-contract offer-id="offer-1" hourly-wage="18.00"/>
		<contact fname="Anna" lname="Bolika" phonenumber="715428429" e-mail="anna@gmx.at"/>
	</company>
	<company id="company-4" name="Scheffknecht Transporte">
		<address country="AUT" zip="6890" city="Lustenau" street="Hagstraße 30"/>
		<company-contract offer-id="offer-5" hourly-wage="8.00"/>
		<company-contract offer-id="offer-5" hourly-wage="8.00"/>
		<contact fname="Hans" lname="Friedl" phonenumber="642844729" e-mail="scheffknecht@hotmail.at"/>
	</company>
	<company id="company-5" name="Elektro Österle GmbH">
		<address country="AUT" zip="6933" city="Doren" street="Schnoran 182"/>
		<contact fname="Hein" lname="Blöd" phonenumber="36168248" e-mail="heinblöd@gmail.at"/>
	</company>
	<company id="company-6" name="Engel Installationen">
		<address country="AUT" zip="6850" city="Dornbirn" street="Schwefel 26"/>
		<company-contract offer-id="offer-3" hourly-wage="15.00"/>
		<company-contract offer-id="offer-3" hourly-wage="7.00"/>
		<company-contract offer-id="offer-3" hourly-wage="7.00"/>
		<contact fname="Erhardt" lname="Engel" phonenumber="05572 22552-3" e-mail="engel.inst@a1.net"/>
	</company>
	<company id="company-7" name="Zimmerman Bau-GmbH">
		<address country="AUT" zip="6900" city="Bregenz" street="Quellenstraße 45"/>
		<company-contract offer-id="offer-2" hourly-wage="17.00"/>
		<company-contract offer-id="offer-2" hourly-wage="17.00"/>
		<company-contract offer-id="offer-2" hourly-wage="17.00"/>
		<contact fname="Sarah" lname="Gmeiner" phonenumber="05574 42979-1" e-mail="sgmein@gmail.at"/>
	</company>
	<company id="company-8" name="Fliesen Felder">
		<address country="AUT" zip="6890" city="Lustenau" street="Mähdlestraße 40"/>
		<company-contract offer-id="offer-4" hourly-wage="10.00"/>
		<company-contract offer-id="offer-4" hourly-wage="7.50"/>
		<contact fname="Else" lname="Prokopic" phonenumber="05577 62535-1" e-mail="else.prokopic@felder.at"/>
	</company>
	
	
	<worker id="worker-1" fname="Paul" lname="Gruber" phonenumber="1983915" e-mail="hshg@gmail.com" qualification="Elektriker">
		<address country="AUT" zip="6850" city="Schwarzenberg" street="Nebengasse 1"/>
		<cv-entry start="12.12.2000" end="02.02.2010" company-name="I+R Gruppe GmbH"/>
		<cv-entry start="01.03.2010" end="30.08.2016" company-name="JoviTech"/>
		<cv-entry start="12.11.2016" end="01.01.2017" company-name="Blum"/>
		<cv-entry start="04.01.2017" end="19.04.2017" company-name="GBWeiß"/>
		<cv-entry start="20.04.2018" end="12.12.2018" company-name="Elektro-Willi"/>
		<worker-contract offer-id="offer-1" hourly-wage="17.00"/>
	</worker>
	<worker id="worker-2" fname="Horst" lname="Hammer" phonenumber="7890022" e-mail="horsthg@gmx.com" qualification="Maurer">
		<address country="AUT" zip="6900" city="Bregenz" street="Leutbühel 2"/>
		<cv-entry start="10.01.1999" end="03.04.2002" company-name="Bachmann"/>
		<cv-entry start="02.12.2000" end="02.09.2005" company-name="I+R Gruppe GmbH"/>
		<cv-entry start="16.09.2005" end="28.10.2011" company-name="Loacker"/>
		<cv-entry start="12.12.2011" end="02.02.2012" company-name="Zimmerman Bau-GmbH"/>
		<cv-entry start="10.04.2012" end="10.04.2018" company-name="Huppenkothen"/>
		<worker-contract offer-id="offer-1" hourly-wage="16.00"/>
		<worker-contract offer-id="offer-2" hourly-wage="16.00"/>
	</worker>
	<worker id="worker-3" fname="Karl" lname="Kleister" phonenumber="1234567" e-mail="kleister.karl@gmail.com" qualification="Gwh-installateur">
		<address country="AUT" zip="6923" city="Lauterach" street="Bundesstrasse 115"/>
		<cv-entry start="19.09.1998" end="02.09.2000" company-name="Karls Klos"/>
		<cv-entry start="12.12.2000" end="02.02.2010" company-name="I+R Gruppe GmbH"/>
		<cv-entry start="05.05.2010" end="30.8.2013" company-name="Heizungen Hubert"/>
		<cv-entry start="03.09.2013" end="20.12.2018" company-name="Summer Sanitär u. Heizungstechnik"/>
		<worker-contract offer-id="offer-1" hourly-wage="17.00"/>
	</worker>
	<worker id="worker-4" fname="Dörthe" lname="Müller" phonenumber="0664 908763" e-mail="doemueg@gmail.com" qualification="Hilfsarbeiter">
		<address country="AUT" zip="6933" city="Doren" street="Hubahn 23"/>
		<cv-entry start="01.01.2013" end="01.02.2015" company-name="Engel Installationen"/>
		<cv-entry start="15.06.2015" end="30.12.2015" company-name="Fliesen Felder"/>
		<cv-entry start="13.09.2017" end="" company-name="Scheffknecht Transporte"/>
		<worker-contract offer-id="offer-3" hourly-wage="6.00"/>
		<worker-contract offer-id="offer-4" hourly-wage="6.00"/>
		<worker-contract offer-id="offer-5" hourly-wage="6.50"/>
	</worker>
	<worker id="worker-5" fname="Tobias" lname="Strnic" phonenumber="0600 8765432" e-mail="tob.str@gmx.at" qualification="Fliesenleger">
		<address country="AUT" zip="6900" city="Bregenz" street="Wolfbergstraße 10"/>
		<cv-entry start="04.01.2013" end="19.08.2015" company-name="Fliesen Form"/>
		<cv-entry start="13.09.2015" end="" company-name="Fliesen Felder"/>
		<worker-contract offer-id="offer-4" hourly-wage="8.00"/>
	</worker>
	<worker id="worker-6" fname="Herbert" lname="Lamprecht" phonenumber="05574 08542" e-mail="herlamp@a1.at" qualification="Klempner">
		<address country="AUT" zip="6850" city="Dornbirn" street="J.G. Ulmerstraße 13"/>
		<cv-entry start="01.01.2013" end="01.09.2015" company-name="Engel Installationen"/>
		<cv-entry start="12.11.15" end="01.01.17" company-name="Tenne Bad und Sanitär"/>
		<cv-entry start="05.02.17" end="20.11.18" company-name="Badmann Installationen"/>
		<worker-contract offer-id="offer-3" hourly-wage="13.00"/>
	</worker>
	<worker id="worker-7" fname="Nenad" lname="Özcan" phonenumber="0600 657843" e-mail="nenad.oezcan@gmail.at" qualification="Zimmerer">
		<address country="AUT" zip="6850" city="Dornbirn" street="Hoschulstraße 20"/>
		<cv-entry start="12.12.2011" end="02.02.2012" company-name="Zimmermann Bau-GmbH"/>
		<cv-entry start="05.04.2012" end="20.11.18" company-name="Holzmann"/>
		<worker-contract offer-id="offer-2" hourly-wage="14.50"/>
	</worker>
	<worker id="worker-8" fname="Markus" lname="Österle" phonenumber="0664 908070" e-mail="markus.oe@a1.net" qualification="Dachdecker">
		<address country="AUT" zip="6900" city="Bregenz" street="Gallusstraße 37"/>
		<cv-entry start="12.12.2011" end="02.02.2012" company-name="Zimmermann Bau-GmbH"/>
		<cv-entry start="01.10.2012" end="25.12.2018" company-name="Zimmerei Berchtel GmbH"/>
		<worker-contract offer-id="offer-2" hourly-wage="13.50"/>
	</worker>
	<worker id="worker-9" fname="Erich" lname="Schneider" phonenumber="0664 934570" qualification="Elektriker">
		<address country="AUT" zip="6900" city="Bregenz" street="Bergstraße 6"/>
		<cv-entry start="06.06.1990" end="06.06.2017" company-name="Elektro Pluschnig GmbH"/>
	</worker>
	<worker id="worker-10" fname="Christina" lname="Grabher" phonenumber="0664 900998" e-mail="grabher.christina@gmx.at" qualification="Elektriker">
		<address country="AUT" zip="6900" city="Bregenz" street="Arlbergstraße 75"/>
		<cv-entry start="05.04.1999" end="10.10.2005" company-name="I+R Gruppe GmbH"/>
		<cv-entry start="03.04.2006" end="10.10.2017" company-name="Elektro-Willie"/>
	</worker>
	<worker id="worker-11" fname="Emil" lname="Nussbaumer" phonenumber="0660 890998" qualification="Hilfsarbeiter">
		<address country="AUT" zip="6850" city="Dorbirn" street="Wallenmahd 22"/>
		<cv-entry start="01.01.2007" end="31.12.2008" company-name="I+R Gruppe GmbH"/>
		<cv-entry start="01.01.2009" end="31.12.2010" company-name="Flatz"/>
		<cv-entry start="01.01.2011" end="31.12.2012" company-name="Collini"/>
		<cv-entry start="01.01.2013" end="01.02.2015" company-name="Engel Installationen"/>
		<cv-entry start="01.04.2015" end="31.07.2017" company-name="Blum"/>
		<cv-entry start="13.09.2017" end="" company-name="Scheffknecht Transporte"/>
		<worker-contract offer-id="offer-3" hourly-wage="6.00"/>
		<worker-contract offer-id="offer-5" hourly-wage="6.50"/>
	</worker>
	
	<request id="request-1">
		<denied-worker worker-id="worker-10"/>
		<request-entry start="12.12.2000" end="02.02.2010" qualification="Elektriker"/>
		<request-entry start="12.12.2000" end="02.02.2010" qualification="Gwh-installateur"/>
		<request-entry start="02.12.2000" end="02.09.2005" qualification="Maurer"/>		
	</request>
	<request id="request-2">
		<request-entry start="12.12.2011" end="02.02.2012" qualification="Dachdecker"/>
		<request-entry start="12.12.2011" end="02.02.2012" qualification="Zimmerer"/>
		<request-entry start="12.12.2011" end="02.02.2012" qualification="Maurer"/>		
	</request>
	<request id="request-3">
		<denied-worker worker-id="worker-1"/>
		<request-entry start="01.01.2013" end="01.09.2015" qualification="Klempner"/>
		<request-entry start="01.01.2013" end="01.02.2015" qualification="Hilfsarbeiter"/>	
		<request-entry start="01.01.2013" end="01.02.2015" qualification="Hilfsarbeiter"/>		
	</request>
	<request id="request-4">
		<denied-worker worker-id="worker-11"/>
		<request-entry start="13.09.2015" qualification="Fliesenleger"/>
