=== geschwaerzler/xml-examples/lab/lab1/Bernhard_Birbamer_Griesser_Kaufmann/tournament.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT tournament (division|participant|waitlist|event|target|age-class)*>
<!ATTLIST tournament
        name            CDATA #REQUIRED
>

<!ELEMENT division (#PCDATA)>
<!ATTLIST division
        category        CDATA #REQUIRED
        id              ID #REQUIRED
        maxage          CDATA #REQUIRED
        minage          CDATA #REQUIRED
>

<!ELEMENT participant (shooting-style|gender|match)*>
<!ATTLIST participant
        age             CDATA #REQUIRED
        dev-id          IDREF #REQUIRED
        fname           CDATA #REQUIRED
        lname           CDATA #REQUIRED
        regno           ID #REQUIRED
        age-class       IDREF #REQUIRED
>

<!ELEMENT shooting-style (#PCDATA)>
<!ATTLIST shooting-style
        bowtype         CDATA #REQUIRED
>

<!ELEMENT gender (#PCDATA)>
<!ATTLIST gender
        gender          ( m | f ) #REQUIRED
>

<!ELEMENT match (scoring)*>
<!ATTLIST match
        event-id        IDREF #REQUIRED
>

<!ELEMENT scoring (table)*>

<!ELEMENT table (arrow)*>
<!ATTLIST table
        target-id       IDREF #REQUIRED
>

<!ELEMENT arrow (#PCDATA)>
<!ATTLIST arrow
        arrow-nr        CDATA #REQUIRED
        points          CDATA #REQUIRED
>

<!ELEMENT waitlist (#PCDATA)>
<!ATTLIST waitlist
        regno           ID #REQUIRED
        date            CDATA #REQUIRED
>

<!ELEMENT event (place)*>
<!ATTLIST event
        comment         CDATA #REQUIRED
        date            CDATA #REQUIRED
        id              ID #REQUIRED
>

<!ELEMENT place (#PCDATA)>
<!ATTLIST place
        address         CDATA #REQUIRED
        place-id        ID #REQUIRED
>

<!ELEMENT target (#PCDATA)>
<!ATTLIST target
        id              ID #REQUIRED
>

<!ELEMENT age-class  (#PCDATA)>
<!ATTLIST age-class
        age-class-id    ID #REQUIRED
        maxage          CDATA #REQUIRED
        minage          CDATA #REQUIRED
>

=== geschwaerzler/xml-examples/lab/lab1/Bernhard_Birbamer_Griesser_Kaufmann/tournament.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE tournament SYSTEM "tournament.dtd">

<tournament name="FH Open 2021">

	<division id="D1" category="1" minage="20" maxage="30"/>
	<division id="D2" category="2" minage="20" maxage="30"/>

	<participant regno="P1" fname="Lukas" lname="Kaufmann" age="25" dev-id="D1" age-class="AGE1">
		<shooting-style bowtype="longbow"/>
		<shooting-style bowtype="compound"/>
		<gender gender="m"/>
		
		<match event-id="E-1">
			<scoring>
				<table target-id="T-1">
					<arrow arrow-nr="1" points="7" />
					<arrow arrow-nr="2" points="10" />
					<arrow arrow-nr="3" points="4" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="9" />
					<arrow arrow-nr="6" points="9" />
				</table>
				<table target-id="T-2">
					<arrow arrow-nr="1" points="8" />
					<arrow arrow-nr="2" points="9" />
					<arrow arrow-nr="3" points="7" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="5" />
					<arrow arrow-nr="6" points="10" />
				</table>
			</scoring>
		</match>
		
		<match event-id="E-2">
			<scoring>
				<table target-id="T-1">
					<arrow arrow-nr="1" points="7" />
					<arrow arrow-nr="2" points="10" />
					<arrow arrow-nr="3" points="4" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="9" />
					<arrow arrow-nr="6" points="9" />
				</table>
				<table target-id="T-2">
					<arrow arrow-nr="1" points="8" />
					<arrow arrow-nr="2" points="9" />
					<arrow arrow-nr="3" points="7" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="5" />
					<arrow arrow-nr="6" points="10" />
				</table>
			</scoring>
		</match>
	</participant>
	
	<participant regno="P2" fname="Pierre" lname="Gröber" age="23" dev-id="D2" age-class="AGE1">
		<shooting-style bowtype="recurve"/>
		<gender gender="m"/>
		
		<match event-id="E-1">
			<scoring>
				<table target-id="T-1">
					<arrow arrow-nr="1" points="7" />
					<arrow arrow-nr="2" points="10" />
					<arrow arrow-nr="3" points="4" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="9" />
					<arrow arrow-nr="6" points="9" />
				</table>
				<table target-id="T-2">
					<arrow arrow-nr="1" points="8" />
					<arrow arrow-nr="2" points="9" />
					<arrow arrow-nr="3" points="7" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="5" />
					<arrow arrow-nr="6" points="10" />
				</table>
			</scoring>
		</match>
		
		<match event-id="E-2">
			<scoring>
				<table target-id="T-1">
					<arrow arrow-nr="1" points="7" />
					<arrow arrow-nr="2" points="10" />
					<arrow arrow-nr="3" points="4" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="9" />
					<arrow arrow-nr="6" points="9" />
				</table>
				<table target-id="T-2">
					<arrow arrow-nr="1" points="8" />
					<arrow arrow-nr="2" points="9" />
					<arrow arrow-nr="3" points="7" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="5" />
					<arrow arrow-nr="6" points="10" />
				</table>
			</scoring>
		</match>
	</participant>
	
	<participant regno="P3" fname="Dario" lname="Birbamer" age="21" dev-id="D2" age-class="AGE1">
		<shooting-style bowtype="recurve"/>
		<gender gender="m"/>
		
		<match event-id="E-1">
			<scoring>
				<table target-id="T-1">
					<arrow arrow-nr="1" points="7" />
					<arrow arrow-nr="2" points="10" />
					<arrow arrow-nr="3" points="4" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="9" />
					<arrow arrow-nr="6" points="9" />
				</table>
				<table target-id="T-2">
					<arrow arrow-nr="1" points="8" />
					<arrow arrow-nr="2" points="9" />
					<arrow arrow-nr="3" points="7" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="5" />
					<arrow arrow-nr="6" points="10" />
				</table>
			</scoring>
		</match>
		
		<match event-id="E-2">
			<scoring>
				<table target-id="T-1">
					<arrow arrow-nr="1" points="7" />
					<arrow arrow-nr="2" points="10" />
					<arrow arrow-nr="3" points="4" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="9" />
					<arrow arrow-nr="6" points="9" />
				</table>
				<table target-id="T-2">
					<arrow arrow-nr="1" points="8" />
					<arrow arrow-nr="2" points="9" />
					<arrow arrow-nr="3" points="7" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="5" />
					<arrow arrow-nr="6" points="10" />
				</table>
			</scoring>
		</match>
	</participant>
	
	<participant regno="P4" fname="Julian" lname="Grießer" age="21" dev-id="D1" age-class="AGE1">
		<shooting-style bowtype="recurve"/>
		<gender gender="m"/>
		
		<match event-id="E-1">
			<scoring>
				<table target-id="T-1">
					<arrow arrow-nr="1" points="7" />
					<arrow arrow-nr="2" points="10" />
					<arrow arrow-nr="3" points="4" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="9" />
					<arrow arrow-nr="6" points="9" />
				</table>
				<table target-id="T-2">
					<arrow arrow-nr="1" points="8" />
					<arrow arrow-nr="2" points="9" />
					<arrow arrow-nr="3" points="7" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="5" />
					<arrow arrow-nr="6" points="10" />
				</table>
			</scoring>
		</match>
		
		<match event-id="E-2">
			<scoring>
				<table target-id="T-1">
					<arrow arrow-nr="1" points="7" />
					<arrow arrow-nr="2" points="10" />
					<arrow arrow-nr="3" points="4" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="9" />
					<arrow arrow-nr="6" points="9" />
				</table>
				<table target-id="T-2">
					<arrow arrow-nr="1" points="8" />
					<arrow arrow-nr="2" points="9" />
					<arrow arrow-nr="3" points="7" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="5" />
					<arrow arrow-nr="6" points="10" />
				</table>
			</scoring>
		</match>
	</participant>
	
	<participant regno="P5" fname="Adrian" lname="Bernhard" age="22" dev-id="D1" age-class="AGE1">
		<shooting-style bowtype="recurve"/>
		<gender gender="m"/>
		
		<match event-id="E-1">
			<scoring>
				<table target-id="T-1">
					<arrow arrow-nr="1" points="7" />
					<arrow arrow-nr="2" points="10" />
					<arrow arrow-nr="3" points="4" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="9" />
					<arrow arrow-nr="6" points="9" />
				</table>
				<table target-id="T-2">
					<arrow arrow-nr="1" points="8" />
					<arrow arrow-nr="2" points="9" />
					<arrow arrow-nr="3" points="7" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="5" />
					<arrow arrow-nr="6" points="10" />
				</table>
			</scoring>
		</match>
		
		<match event-id="E-2">
			<scoring>
				<table target-id="T-1">
					<arrow arrow-nr="1" points="7" />
					<arrow arrow-nr="2" points="10" />
					<arrow arrow-nr="3" points="4" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="9" />
					<arrow arrow-nr="6" points="9" />
				</table>
				<table target-id="T-2">
					<arrow arrow-nr="1" points="8" />
					<arrow arrow-nr="2" points="9" />
					<arrow arrow-nr="3" points="7" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="5" />
					<arrow arrow-nr="6" points="10" />
				</table>
			</scoring>
		</match>
	</participant>
	
	<waitlist regno="W4" date="2020-12-12"/>
	
	<event id="E-1" date="2021-05-26" comment="">
		<place place-id="PL1" address="Hard"/>
	</event>

	<event id="E-2" date="2021-05-27" comment="">
		<place place-id="PL2" address="Dornbirn"/>
	</event>

	<target id="T-1"/>
	<target id="T-2"/>

	<age-class age-class-id="AGE1" minage="20" maxage="30"/>

</tournament>

=== geschwaerzler/xml-examples/lab/lab3/BernhardBirbamerGriesserKaufmann/tournament.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE tournament SYSTEM "tournament.dtd">

<tournament name="FH Open 2021">

	<division id="D1" category="1" minage="20" maxage="30"/>
	<division id="D2" category="2" minage="20" maxage="30"/>

	<participant regno="P1" fname="Lukas" lname="Kaufmann" gender="m" age="25" div-id="D1" age-class="AGE1">
		<shooting-style bowtype="longbow"/>
		<shooting-style bowtype="compound"/>
		
		<match event-id="E-1">
			<scoring>
				<table target-id="T-1">
					<arrow arrow-nr="1" points="10" />
					<arrow arrow-nr="2" points="10" />
					<arrow arrow-nr="3" points="10" />
					<arrow arrow-nr="4" points="10" />
					<arrow arrow-nr="5" points="10" />
					<arrow arrow-nr="6" points="10" />
				</table>
				<table target-id="T-2">
					<arrow arrow-nr="1" points="10" />
					<arrow arrow-nr="2" points="10" />
					<arrow arrow-nr="3" points="10" />
					<arrow arrow-nr="4" points="10" />
					<arrow arrow-nr="5" points="10" />
					<arrow arrow-nr="6" points="10" />
				</table>
			</scoring>
		</match>
		
		<match event-id="E-2">
			<scoring>
				<table target-id="T-1">
					<arrow arrow-nr="1" points="7" />
					<arrow arrow-nr="2" points="10" />
					<arrow arrow-nr="3" points="4" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="9" />
					<arrow arrow-nr="6" points="9" />
				</table>
				<table target-id="T-2">
					<arrow arrow-nr="1" points="8" />
					<arrow arrow-nr="2" points="9" />
					<arrow arrow-nr="3" points="9" />
					<arrow arrow-nr="4" points="9" />
					<arrow arrow-nr="5" points="5" />
					<arrow arrow-nr="6" points="10" />
				</table>
			</scoring>
		</match>
	</participant>
	
	<participant regno="P2" fname="Pierre" lname="Gröber" gender="m" age="23" div-id="D2" age-class="AGE1">
		<shooting-style bowtype="recurve"/>
		
		<match event-id="E-1">
			<scoring>
				<table target-id="T-1">
					<arrow arrow-nr="1" points="0" />
					<arrow arrow-nr="2" points="0" />
					<arrow arrow-nr="3" points="0" />
					<arrow arrow-nr="4" points="0" />
					<arrow arrow-nr="5" points="0" />
					<arrow arrow-nr="6" points="0" />
				</table>
				<table target-id="T-2">
					<arrow arrow-nr="1" points="0" />
					<arrow arrow-nr="2" points="0" />
					<arrow arrow-nr="3" points="0" />
					<arrow arrow-nr="4" points="0" />
					<arrow arrow-nr="5" points="0" />
					<arrow arrow-nr="6" points="1" />
				</table>
			</scoring>
		</match>
		
		<match event-id="E-2">
			<scoring>
				<table target-id="T-1">
					<arrow arrow-nr="1" points="7" />
					<arrow arrow-nr="2" points="10" />
					<arrow arrow-nr="3" points="4" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="7" />
					<arrow arrow-nr="6" points="9" />
				</table>
				<table target-id="T-2">
					<arrow arrow-nr="1" points="8" />
					<arrow arrow-nr="2" points="7" />
					<arrow arrow-nr="3" points="7" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="5" />
					<arrow arrow-nr="6" points="10" />
				</table>
			</scoring>
		</match>
	</participant>
	
	<participant regno="P3" fname="Dario" lname="Birbamer" gender="m" age="21" div-id="D2" age-class="AGE1">
		<shooting-style bowtype="recurve"/>
		
		<match event-id="E-1">
			<scoring>
				<table target-id="T-1">
					<arrow arrow-nr="1" points="7" />
					<arrow arrow-nr="2" points="10" />
					<arrow arrow-nr="3" points="4" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="6" />
					<arrow arrow-nr="6" points="9" />
				</table>
				<table target-id="T-2">
					<arrow arrow-nr="1" points="8" />
					<arrow arrow-nr="2" points="9" />
					<arrow arrow-nr="3" points="7" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="5" />
					<arrow arrow-nr="6" points="6" />
				</table>
			</scoring>
		</match>
		
		<match event-id="E-2">
			<scoring>
				<table target-id="T-1">
					<arrow arrow-nr="1" points="7" />
					<arrow arrow-nr="2" points="10" />
					<arrow arrow-nr="3" points="4" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="9" />
					<arrow arrow-nr="6" points="9" />
				</table>
				<table target-id="T-2">
					<arrow arrow-nr="1" points="8" />
					<arrow arrow-nr="2" points="9" />
					<arrow arrow-nr="3" points="7" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="5" />
					<arrow arrow-nr="6" points="10" />
				</table>
			</scoring>
		</match>
	</participant>
	
	<participant regno="P4" fname="Julian" lname="Grießer" gender="m" age="21" div-id="D1" age-class="AGE1">
		<shooting-style bowtype="recurve"/>
		
		<match event-id="E-1">
			<scoring>
				<table target-id="T-1">
					<arrow arrow-nr="1" points="7" />
					<arrow arrow-nr="2" points="10" />
					<arrow arrow-nr="3" points="4" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="9" />
					<arrow arrow-nr="6" points="9" />
				</table>
				<table target-id="T-2">
					<arrow arrow-nr="1" points="8" />
					<arrow arrow-nr="2" points="9" />
					<arrow arrow-nr="3" points="7" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="5" />
					<arrow arrow-nr="6" points="10" />
				</table>
			</scoring>
		</match>
		
		<match event-id="E-2">
			<scoring>
				<table target-id="T-1">
					<arrow arrow-nr="1" points="7" />
					<arrow arrow-nr="2" points="10" />
					<arrow arrow-nr="3" points="4" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="9" />
					<arrow arrow-nr="6" points="9" />
				</table>
				<table target-id="T-2">
					<arrow arrow-nr="1" points="8" />
					<arrow arrow-nr="2" points="9" />
					<arrow arrow-nr="3" points="7" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="5" />
					<arrow arrow-nr="6" points="10" />
				</table>
			</scoring>
		</match>
	</participant>
	
	<participant regno="P5" fname="Adrian" lname="Bernhard" gender="m" age="22" div-id="D1" age-class="AGE1">
		<shooting-style bowtype="recurve"/>
		
		<match event-id="E-1">
			<scoring>
				<table target-id="T-1">
					<arrow arrow-nr="1" points="7" />
					<arrow arrow-nr="2" points="10" />
					<arrow arrow-nr="3" points="4" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="9" />
					<arrow arrow-nr="6" points="9" />
				</table>
				<table target-id="T-2">
					<arrow arrow-nr="1" points="8" />
					<arrow arrow-nr="2" points="9" />
					<arrow arrow-nr="3" points="7" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="5" />
					<arrow arrow-nr="6" points="10" />
				</table>
			</scoring>
		</match>
		
		<match event-id="E-2">
			<scoring>
				<table target-id="T-1">
					<arrow arrow-nr="1" points="7" />
					<arrow arrow-nr="2" points="10" />
					<arrow arrow-nr="3" points="4" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="9" />
					<arrow arrow-nr="6" points="9" />
				</table>
				<table target-id="T-2">
					<arrow arrow-nr="1" points="8" />
					<arrow arrow-nr="2" points="9" />
					<arrow arrow-nr="3" points="7" />
					<arrow arrow-nr="4" points="6" />
					<arrow arrow-nr="5" points="5" />
					<arrow arrow-nr="6" points="10" />
				</table>
			</scoring>
		</match>
	</participant>
	
	<waitlist regno="W4" date="2020-12-12"/>
	
	<event id="E-1" date="2021-05-26" comment="">
		<place place-id="PL1" address="Hard"/>
	</event>

	<event id="E-2" date="2021-05-27" comment="">
		<place place-id="PL2" address="Dornbirn"/>
	</event>

	<target id="T-1"/>
	<target id="T-2"/>

	<age-class age-class-id="AGE1" minage="20" maxage="30"/>

</tournament>
